// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFfezEPs3XmZ62x0a68SrWvTSNv1Gp4AY',
    appId: '1:529531720727:web:586778ef283299a69cb852',
    messagingSenderId: '529531720727',
    projectId: 'flash-chat-9296c',
    authDomain: 'flash-chat-9296c.firebaseapp.com',
    storageBucket: 'flash-chat-9296c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsbl2YSSCCQ0jZDdl-46JGaiMT_uac_BI',
    appId: '1:529531720727:android:bd891cd0fb59ce8d9cb852',
    messagingSenderId: '529531720727',
    projectId: 'flash-chat-9296c',
    storageBucket: 'flash-chat-9296c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ0Ge7-HarQQZoKipTXjeVgb2K_1htbUU',
    appId: '1:529531720727:ios:e6e131ea0aa47b0a9cb852',
    messagingSenderId: '529531720727',
    projectId: 'flash-chat-9296c',
    storageBucket: 'flash-chat-9296c.appspot.com',
    iosClientId: '529531720727-vfsanq9cbjkmk303bujl67n8l0efutlg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChatStartingProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ0Ge7-HarQQZoKipTXjeVgb2K_1htbUU',
    appId: '1:529531720727:ios:e6e131ea0aa47b0a9cb852',
    messagingSenderId: '529531720727',
    projectId: 'flash-chat-9296c',
    storageBucket: 'flash-chat-9296c.appspot.com',
    iosClientId: '529531720727-vfsanq9cbjkmk303bujl67n8l0efutlg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChatStartingProject',
  );
}
